### ISSUE TITLE
readme urls

### ISSUE THREAD

**Issue by mikejohnson51** [YingjieHu/BalancedConcaveHull#1]
Hi Yingjie, 

This looks like a great peice of work!

Just wanted to note the urls (to images and urbanPOIs) are broken in the README.

Thanks!

Mike

**Comment by YingjieHu** [comment]
Thank you Mike for the message! 

The UrbanAOI online demo was published on a UCSB server, which was no longer maintained after I have graduated from UCSB. I will try to fix the image links soon. Thanks for letting me know this issue!

Cheers,
Yingjie

**Comment by mikejohnson51** [comment]
Thanks! They look great,

Mike
